// Code generated by "callbackgen -type FileWatcher"; DO NOT EDIT.

package syncbox

import ()

func (f *FileWatcher) OnChange(cb func(files []File)) {
	f.changeCallbacks = append(f.changeCallbacks, cb)
}

func (f *FileWatcher) EmitChange(files []File) {
	for _, cb := range f.changeCallbacks {
		cb(files)
	}
}
