// Code generated by "callbackgen -type SyncClient"; DO NOT EDIT.

package syncbox

import ()

func (s *SyncClient) OnFileChange(cb func(files []File)) {
	s.fileChangeCallbacks = append(s.fileChangeCallbacks, cb)
}

func (s *SyncClient) EmitFileChange(files []File) {
	for _, cb := range s.fileChangeCallbacks {
		cb(files)
	}
}
