// Code generated by "callbackgen -type SyncServer"; DO NOT EDIT.

package syncbox

import ()

func (S *SyncServer) OnMessage(cb func(conn *SyncConnection, message []byte)) {
	S.messageCallbacks = append(S.messageCallbacks, cb)
}

func (S *SyncServer) EmitMessage(conn *SyncConnection, message []byte) {
	for _, cb := range S.messageCallbacks {
		cb(conn, message)
	}
}
